language: scala

scala:
  - 2.10.6

jdk:
  - oraclejdk8

sudo: false

before_install:
  - ./install-dependencies.sh

script:
  - sbt warn clean reload compile coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)