language: scala

scala:
  - 2.10.6

jdk:
  - oraclejdk8

before_install:
  - ./install-dependencies.sh

script:
  - sbt clean reload compile

after_success:
  - bash <(curl -s https://codecov.io/bash)