language: scala

scala:
   - 2.10.6

sudo: required
dist: trusty

before_install:
  - sudo bash install-dependencies.sh

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)